### ISSUE TITLE
Parse request body

### ISSUE THREAD

**Issue by iuryr** [thaisnishimoto/42sp_Webserv#6]
# When to expect a body?

- [ ] When header structure has a Content-length key with a positive value;
- [ ] When header structure has a Transfer-Encoding with `chunked` value;
- [ ] GET and HEAD verbs allow for the presence of body, but it is usually IGNORED.
- [ ] POST always has a body
- [ ] DELETE **may** have a body (it is rare, though);

If there is a `Conten-Length` and `Transfer-Encoding` on the same Request, the appropriate status responde is 400 Bad Request.

---
1. Se o método for GET, não tentamos parsear o body.
2. Se o método for POST ou DELETE, verificamos a existência de `Transfer-Encoding` e `Content-Length` para decidir se parseamos o body.

Primeiro vamos focar na situação de `Content-Length`.

**Comment by thaisnishimoto** [comment]
### Parse request including the body
1. epoll_wait with a timeout
2. accept new connection and add to epoll instance
3. recv request (partial or whole)
4. get request line and validate (add max request line length?)
5. get headers and validate (add max header size and count?)
- when host header, check for match in virtual server, the path location and if accepts the method of the request line
- already checks if max one body type header, and if transfer encoding, only accepts chunked
6. if content-length header, read buffer and append until body size is equal content-lenght
7. else if chunked, read and append until final chunk and validate chunks (proper termination, no extra parameters, avoid overflow)
- if body is incomplete, return to epoll_wait to get the rest. On epoll timeout, iterate through connections to send a 408 Request Timeout for those that have exceeded their deadlines. 
9. Swich to epollout to generate response

**Comment by iuryr** [comment]
# TODO

- [ ] Content-Length without any values should 400 bad request (do not interpret empty value as zero)
- [ ] Check string for chars other than digits
- [ ] Parse string into numeric value and check constraints

**Comment by iuryr** [comment]
# Parse Body (Transfer-Encoding)
---

- [ ] Verificar de um existência do header-field Transfer-Encoding
- [ ]
